version: '3.4'
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.21.1
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_TIMEOUT: "600"
    restart: always
    logging: *default-logging
