version: '3.4'
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  frontend:
    image: lblod/frontend-reglementaire-bijlage:latest
    restart: always
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
  login:
    image: lblod/acmidm-login-service:feature-configurable
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op/.well-known/openid-configuration"
      MU_APPLICATION_AUTH_CLIENT_ID: "69069b1c-0bd0-4679-a9af-5a265c544c1c"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://reglementairebijlagen.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_lblod_rol_3d"
      MU_APPLICATION_AUTH_GROUPID_CLAIM: "vo_ovocode"
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:feature-nicer-error-on-unfound-resource-specification
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_TIMEOUT: "600"
    restart: always
    logging: *default-logging
