version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    environment:
      ENABLE_CORS: "true"
    ports:
      - "8890:8890"
  resource:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  migrations:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
  yasgui:
    image: erikap/yasgui
    ports:
      - "8891:80"
    environment:
      ENABLE_ENDPOINT_SELECTOR: "true"
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
